// ─── STRATEGY PLAYBOOK — per industry+mode contextual guidance shown in-game ───
export const STRATEGY_PLAYBOOK: Record<string, {
    model: string; customers: string; mrrFormula: string; growthLever: string; mainRisk: string;
    marketingTip: string; hiringPriority: string; statFocus: string;
}> = {
    "SaaS Platform_PLG": {
        model: "Self-Serve SaaS",
        customers: "SMBs and individual professionals who sign up themselves via free trial.",
        mrrFormula: "Paid Users × Monthly Price",
        growthLever: "Paid rate depends on PMF, Quality, & Price. Product virality drives Total Users.",
        mainRisk: "High churn if product quality drops. Users leave fast when frustrated.",
        marketingTip: "Organic social and content marketing bring low-CAC signups. Keep investing.",
        hiringPriority: "Hire Engineers first to build a reliable product, then Growth Marketers.",
        statFocus: "Watch PMF Score and Churn. Both must improve together.",
    },
    "SaaS Platform_SLG": {
        model: "Enterprise SaaS",
        customers: "IT leads and VPs at mid-to-large companies. Decisions take months.",
        mrrFormula: "Active Contracts × Contract Value",
        growthLever: "Sales pipeline — outbound demos, proposals, and relationship building.",
        mainRisk: "Long sales cycles. Revenue ramps slowly before the first few big wins.",
        marketingTip: "PR and brand credibility matter more than viral reach. Build case studies.",
        hiringPriority: "Hire Sales first. Your Account Executives close the deals that matter.",
        statFocus: "Track Deals Closed and pipeline velocity. Revenue follows deals, not users.",
    },
    "AI Platform_PLG": {
        model: "Self-Serve API Model",
        customers: "Developers and indie builders who integrate your API into their apps.",
        mrrFormula: "API Calls × Token Price (Usage-Based)",
        growthLever: "Developer adoption via open-source buzz, docs quality, and API sandbox.",
        mainRisk: "GPU compute costs are high. You need volume to reach margin.",
        marketingTip: "Developer content, YouTube demos, and GitHub visibility drive adoption.",
        hiringPriority: "Engineers first for model quality, then DevRel to grow the community.",
        statFocus: "Watch Reliability — if your API goes down, developers will switch instantly.",
    },
    "AI Platform_SLG": {
        model: "Enterprise AI Solutions",
        customers: "CIOs and data leaders at large corporations buying bespoke AI deployments.",
        mrrFormula: "Active Enterprise Contracts × Fixed Solution Price",
        growthLever: "High-touch sales and solutions architects who customize deployments.",
        mainRisk: "Very slow procurement. Deals can take 6-12 months to close.",
        marketingTip: "Whitepapers, analyst reports, and LinkedIn thought leadership build credibility.",
        hiringPriority: "Sales + Solutions Architects. Technical sales matters most here.",
        statFocus: "Product Quality must be very high. Enterprise buyers demand reliability.",
    },
    "OTT / Streaming_PLG": {
        model: "Direct-to-Consumer Streaming",
        customers: "Individual subscribers paying monthly for entertainment content.",
        mrrFormula: "Active Subscribers × Monthly Subscription Price",
        growthLever: "Content quality and hit titles drive word-of-mouth and social buzz.",
        mainRisk: "Massive content investment needed to reduce churn and keep viewers hooked.",
        marketingTip: "PR campaigns around new releases + social clips drive organic acquisition.",
        hiringPriority: "Engineers (for streaming infra reliability) + Marketers (for buzz).",
        statFocus: "Churn is your enemy. High churn means great acquisition but poor retention.",
    },
    "OTT / Streaming_SLG": {
        model: "B2B Content Licensing",
        customers: "Other streaming platforms, airlines, hotels, and distributors that license your catalog.",
        mrrFormula: "Active License Deals × Fixed License Fee",
        growthLever: "Content partnership and enterprise sales to distributors with large audiences.",
        mainRisk: "Capped upside per deal. You don't own the end-user relationship.",
        marketingTip: "Industry events, trade publications, and direct outreach to media buyers.",
        hiringPriority: "Sales (Content Partnership Managers). More deals = more revenue.",
        statFocus: "Track Deals Closed. Each deal pays a fixed retainer regardless of viewer count.",
    },
    "Mobile Game_PLG": {
        model: "F2P Viral Mobile Game",
        customers: "Mass-market casual players who download free and optionally pay for IAPs.",
        mrrFormula: "Ad Revenue (Users × Ad Freq) + IAP Revenue (3% of Users × IAP Value)",
        growthLever: "App store ranking, social sharing loops, and influencer reviews.",
        mainRisk: "Only ~3% of players ever pay. Most revenue comes from a tiny whale segment.",
        marketingTip: "Paid acquisition on Meta/TikTok can scale, but watch ROAS carefully.",
        hiringPriority: "Engineers for game quality and crash-free experience.",
        statFocus: "Balance Ad Frequency slider carefully — too high causes churn.",
    },
    "Mobile Game_SLG": {
        model: "Branded / IP Licensed Game",
        customers: "Movie studios, sports leagues, or brands paying for co-branded game experiences.",
        mrrFormula: "Active License Contracts × Engine/IP License Fee",
        growthLever: "Win brand partnerships — the brand brings their own fanbase and marketing.",
        mainRisk: "Royalties cut margin. Creative control is limited by brand requirements.",
        marketingTip: "Your portfolio of past games and technical demos close deals.",
        hiringPriority: "Sales (Brand Partnership Managers) + senior Engineers for polished demos.",
        statFocus: "Product Quality matters most. Low quality games don't renew contracts.",
    },
    "FinTech_PLG": {
        model: "Consumer Neo-bank / FinTech App",
        customers: "Individual consumers — freelancers, digital nomads, Gen-Z users.",
        mrrFormula: "Transaction Volume × Interchange Rate (e.g. 1.5%)",
        growthLever: "Word-of-mouth from referral bonuses and superior UX vs. legacy banks.",
        mainRisk: "Very thin margins. Heavy regulatory and compliance overhead eats cost.",
        marketingTip: "Referral programs and cashback campaigns are the highest-ROI growth channel.",
        hiringPriority: "Engineers (compliance, security, fraud) first. Regulators will shut you down otherwise.",
        statFocus: "Revenue is transaction volume × %, so User growth is everything.",
    },
    "FinTech_SLG": {
        model: "B2B Embedded Finance API",
        customers: "E-commerce platforms, SaaS apps, and fintechs embedding your payment rails.",
        mrrFormula: "Active API Contracts × Monthly Infrastructure Fee",
        growthLever: "Enterprise sales to platform builders who then distribute to their own users.",
        mainRisk: "Long legal and compliance reviews before a client goes live. Slow ramp.",
        marketingTip: "Developer docs and partner portals matter. B2B buyers research deeply.",
        hiringPriority: "Sales + Engineers. Quality of API and reliability are selling points.",
        statFocus: "Reliability is critical. Payment downtime = immediate contract cancellation.",
    },
    "EdTech_PLG": {
        model: "Direct-to-Learner Platform",
        customers: "Students, professionals, and lifelong learners buying individual courses.",
        mrrFormula: "Active Subscribers × Membership Price (or Course Revenue)",
        growthLever: "SEO, content marketing, and free preview videos drive organic course traffic.",
        mainRisk: "Low course completion rates hurt word-of-mouth and increase refund requests.",
        marketingTip: "YouTube tutorials and SEO articles funnel learners directly to paid courses.",
        hiringPriority: "Marketers for content SEO + Engineers for smooth course UX.",
        statFocus: "PMF Score reflects learner satisfaction. Push it above 60 for viral growth.",
    },
    "EdTech_SLG": {
        model: "Institutional / Corporate Learning",
        customers: "School districts, universities, and HR teams buying multi-seat annual licenses.",
        mrrFormula: "Active Seat Licenses × Annual Price Per Seat",
        growthLever: "Institutional procurement relationships and case studies from known schools.",
        mainRisk: "Procurement is slow — decisions go through committees and budget cycles.",
        marketingTip: "Conference talks and whitepapers build credibility with institutional buyers.",
        hiringPriority: "Sales (Account Executives) who can navigate long B2B procurement cycles.",
        statFocus: "Track Deals Closed. Each deal locks in recurring annual contract revenue.",
    },
    "Dev Tools_PLG": {
        model: "Open-Source / Freemium DevTool",
        customers: "Individual developers and small engineering teams who start free.",
        mrrFormula: "Paid Tier Users × Monthly Price (cloud-hosted version)",
        growthLever: "GitHub stars, Hacker News posts, and dev community adoption.",
        mainRisk: "Very hard to convert free users to paid. Most developers expect free forever.",
        marketingTip: "Open-source the core, charge for the hosted/managed version. OSS = marketing.",
        hiringPriority: "Engineers to keep the core product sharp + DevRel / Developer Advocate.",
        statFocus: "Product Quality and Tech Debt define your developer reputation. Keep them healthy.",
    },
    "Dev Tools_SLG": {
        model: "Enterprise DevTool Platform",
        customers: "Engineering organizations at large companies needing SSO, audit logs, compliance.",
        mrrFormula: "Active Enterprise Contracts × Monthly SSO/Cloud Package Price",
        growthLever: "Account Executives targeting CTOs and VPs of Engineering at scale-ups.",
        mainRisk: "Enterprise roadmap pressure slows innovation. Sales drives what gets built.",
        marketingTip: "Security and compliance certifications (SOC2, ISO 27001) are more powerful than ads.",
        hiringPriority: "Sales AEs + Engineers for compliance features. Security is table stakes.",
        statFocus: "Reliability is non-negotiable for dev tools in production environments.",
    },
    "Marketplace_PLG": {
        model: "Community Marketplace",
        customers: "Organic buyers and sellers who discover each other through search and reviews.",
        mrrFormula: "GMV (Transaction Volume) × Take Rate %",
        growthLever: "Supply-side growth (more sellers = more inventory = more buyers).",
        mainRisk: "Cold-start problem — hard to attract buyers without supply and vice versa.",
        marketingTip: "SEO and PR drive buyer intent. Seller referrals grow supply side cheaply.",
        hiringPriority: "Engineers (search, trust & safety) + Marketers (SEO, demand gen).",
        statFocus: "User count = both buyers and sellers. GMV and take rate drive revenue.",
    },
    "Marketplace_SLG": {
        model: "Managed Marketplace",
        customers: "Curated enterprise vendors and suppliers you vet and manage directly.",
        mrrFormula: "Active Supplier Contracts × Monthly Retainer Fee",
        growthLever: "Quality curation and guarantees attract premium buyers who pay more.",
        mainRisk: "Operations-heavy. Each new supplier requires manual vetting and onboarding.",
        marketingTip: "White-glove service reputation and case studies attract premium enterprise buyers.",
        hiringPriority: "Sales (Merchant Success + onboarding) + Engineers for ops automation.",
        statFocus: "Track Deals Closed. Each managed vendor is a fixed retainer contract.",
    },
};
